PIPELINE IMPROVMENTS

diff --git a/.github/workflows/build-bindings.yml b/.github/workflows/build-bindings.yml
--- a/.github/workflows/build-bindings.yml
+++ b/.github/workflows/build-bindings.yml
@@ -317,233 +317,234 @@ jobs:
         status: ${{ job.status }}
         context: ${{ env.STATUS_CHECK_MESSAGE }}
 
-  test-self-hosted:
-    needs: cibuildbinding
-    # There's a top-level env variable for this but we can't use it here, unfortunately
-    if: ${{ inputs.run_tests && (inputs.platform-tag == 'macosx_arm64' || inputs.platform-tag == 'win_amd64') }}
-    strategy:
-      fail-fast: false
-      matrix:
-        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
-    runs-on: ${{ inputs.platform-tag == 'macosx_arm64' && fromJSON('["self-hosted", "macOS", "ARM64", "SMA"]') || fromJSON('["self-hosted", "Windows", "X64"]') }}
-    env:
-      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
-    steps:
-      - name: Create status check message
-        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
-        shell: bash
-
-      - name: Show job status for commit
-        uses: myrotvorets/set-commit-status-action@v2.0.0
-        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
-        with:
-          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-          context: ${{ env.STATUS_CHECK_MESSAGE }}
-
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-
-      # Need to be able to save Docker Hub credentials to keychain
-      - if: ${{ inputs.platform-tag == 'macosx_arm64' && inputs.use-server-rc }}
-        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
-
-      - name: Remove aerospike docker image
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        run: |
-          if docker ps -aq | grep -q .; then
-            docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
-          else
-            echo "No containers to remove."
-          fi
-
-      - name: Remove aerospike docker image
-        if: ${{ inputs.platform-tag == 'win_amd64' }}
-        run: |
-          if (docker ps -aq) {
-              docker ps -aq | ForEach-Object { docker rm -f $_ } || Write-Host "Failed to remove one or more containers."
-          }
-          else {
-              Write-Host "No containers to remove."
-          }
-
-      - uses: ./.github/actions/run-ee-server
-        with:
-          use-server-rc: ${{ inputs.use-server-rc }}
-          server-tag: ${{ inputs.server-tag }}
-          docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
-          docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
-
-      - name: Download wheel
-        uses: actions/download-artifact@v4
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        with:
-          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
-          name: ${{ env.BUILD_IDENTIFIER }}.node
-
-      - name: Download wheel
-        uses: actions/download-artifact@v4
-        if: ${{ inputs.platform-tag == 'win_amd64' }}
-        with:
-          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-win32-x64/
-          name: ${{ env.BUILD_IDENTIFIER }}.node
-
-      - name: Convert Python tag to Python version
-        # Don't use sed because we want this command to work on both mac and windows
-        # The command used in GNU sed is different than in macOS sed
-        run: |
-          NODEJS_TAG=${{ matrix.nodejs-tag[0] }}
-          NODEJS_VERSION="${NODEJS_TAG/cp/}"
-          echo NODEJS_VERSION="${NODEJS_VERSION/3/3.}" >> $GITHUB_ENV
-        shell: bash
-
-      - uses: actions/setup-node@v4
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        with:
-          node-version: ${{ matrix.nodejs-tag[1] }}
-          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
-
-      - uses: actions/setup-node@v4
-        if: ${{ inputs.platform-tag == 'win_amd64' }}
-        with:
-          node-version: ${{ matrix.nodejs-tag[1] }}
-          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-win32-x64/
-
-
-#      - name: Install nvm
-#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#        run: |
-#          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
-#          touch ~/.zprofile
-#          source ~/.zprofile
-#          nvm -v
+#  test-self-hosted:
+#    needs: cibuildbinding
+#    # There's a top-level env variable for this but we can't use it here, unfortunately
+#    if: ${{ inputs.run_tests && (inputs.platform-tag == 'macosx_arm64' || inputs.platform-tag == 'win_amd64') }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
+#    runs-on: ${{ inputs.platform-tag == 'macosx_arm64' && fromJSON('["self-hosted", "macOS", "ARM64", "SMA"]') || fromJSON('["self-hosted", "Windows", "X64"]') }}
+#    env:
+#      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+#    steps:
+#      - name: Create status check message
+#        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
 #        shell: bash
 #
-#      #- name: Install Node.js 20
-#      #  if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#      #  run: |
-#      #    nvm i 20
-#      #  shell: bash
+#      - name: Show job status for commit
+#        uses: myrotvorets/set-commit-status-action@v2.0.0
+#        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+#        with:
+#          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+#          context: ${{ env.STATUS_CHECK_MESSAGE }}
 #
-#      - name: Prepare /usr/local/opt directory
-#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#        run: |
-#          sudo rm -rf /usr/local/opt
-#          sudo mkdir -p /usr/local/opt
-#          sudo chown -R $(whoami) /usr/local/opt
-#        shell: bash
+#      - uses: actions/checkout@v4
+#        with:
+#          ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
 #
-#      - name: Install libuv
-#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#        run: |
-#          brew install libuv
-#          sudo ln -s /opt/homebrew/opt/libuv/1.45.0/ /usr/local/opt/libuv
-#        shell: bash
+#      # Need to be able to save Docker Hub credentials to keychain
+#      - if: ${{ inputs.platform-tag == 'macosx_arm64' && inputs.use-server-rc }}
+#        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
 #
-#      - name: Configure OpenSSL
+#      - name: Remove aerospike docker image
 #        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
 #        run: |
-#          rm -rf /usr/local/opt/openssl
-#          sudo ln -s /opt/homebrew/opt/openssl@3.4/ /usr/local/opt/openssl
-#        shell: bash
+#          if docker ps -aq | grep -q .; then
+#            docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+#          else
+#            echo "No containers to remove."
+#          fi
 #
-#      - name: Update PATH and environment variables
-#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#        run: |
-#          echo "export PATH=\"/usr/local/bin/:/usr/local/opt/openssl/bin:\$PATH\"" >> ~/.zprofile
-#          echo "export LDFLAGS=\"-L/usr/local/opt/openssl/lib\"" >> ~/.zprofile
-#          echo "export CPPFLAGS=\"-I/usr/local/opt/openssl/include\"" >> ~/.zprofile
-#          echo "export EXT_CFLAGS=\"-I/usr/local/opt/openssl/include\"" >> ~/.zprofile
-#        shell: bash
-#
-#      - name: Source updated environment variables
-#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#        run: |
-#          source ~/.zprofile
-#        shell: bash
-
-#      - name: Install wheel
-#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-#        run: |
-#          ./scripts/build-c-client.sh
-#          npm install
-#        shell: bash
-
-#      - name: Install wheel
+#      - name: Remove aerospike docker image
 #        if: ${{ inputs.platform-tag == 'win_amd64' }}
 #        run: |
-#          ./scripts/build-c-client.ps1
-#          npm install
-#        shell: powershell
-
-      - name: Connect to Docker container on remote machine with Docker daemon
-        if: ${{ inputs.platform-tag == 'win_amd64' }}
-        # DOCKER_HOST contains the IP address of the remote machine
-        run: |
-          $env:DOCKER_HOST_IP = $env:DOCKER_HOST | foreach {$_.replace("tcp://","")} | foreach {$_.replace(":2375", "")}
-          crudini --set config.conf enterprise-edition hosts ${env:DOCKER_HOST_IP}:3000
-        working-directory: .github\workflows
-
-      ## FIGURE OUT WHAT SETUP NEEDS TO HAPPEN
-      #- run: |
-      #    npm install typescript --save-dev
-      #    npx tsc;
-      #  working-directory: ts-test
-      #  shell: bash
-
-      #- name: Identify binaries
-      #  if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-      #  run: |
-      #    ls ./lib/binding/node-v108-darwin-arm64
-      #    ls ./lib/binding/node-v108-darwin-arm64/aerospike.node
-      #    mkdir -p build;
-      #    mkdir -p build/Release;
-      #    cp -r ./lib/binding/node-v108-darwin-arm64 build/Release
-
-      - name: Run tests
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        run: |
-          docker ps;
-          docker logs aerospike;
-          cd ts-test;
-          npm uninstall tsc;
-          npm install ..;
-          npm i --save-dev @types/chai;
-          npm i --save-dev @types/jest;
-          npm i --save-dev @types/mocha;
-          npm install mocha;
-          rm -rf dist;
-          npx tsc;
-          cd ..;
-          npm install;
-          pwd;
-          npx tsc;
-          npm run test dist/${{ inputs.test-file }} -- --h localhost --port 3000 --U superuser --P superuser;
-
-
-      - name: Run tests
-        if: ${{ inputs.platform-tag == 'win_amd64' }}
-        run: |
-          docker ps;
-          docker logs aerospike;
-          cd ts-test;
-          npm uninstall tsc;
-          npm install ..;
-          npm i --save-dev @types/chai;
-          npm i --save-dev @types/jest;
-          npm i --save-dev @types/mocha;
-          npm install mocha;
-          npx tsc;
-          cp tests\udf.lua dist\udf.lua;
-          npx mocha dist -- --h ${env:DOCKER_HOST_IP} --port 3000 --U superuser --P superuser;
-          cd ..; 
-          npx tsc;
-
-
-      - name: Show job status for commit
-        if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
-        uses: myrotvorets/set-commit-status-action@v2.0.0
-        with:
-          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-          status: ${{ job.status }}
-          context: ${{ env.STATUS_CHECK_MESSAGE }}
+#          if (docker ps -aq) {
+#              docker ps -aq | ForEach-Object { docker rm -f $_ } || Write-Host "Failed to remove one or more containers."
+#          }
+#          else {
+#              Write-Host "No containers to remove."
+#          }
+#
+#      - uses: ./.github/actions/run-ee-server
+#        with:
+#          use-server-rc: ${{ inputs.use-server-rc }}
+#          server-tag: ${{ inputs.server-tag }}
+#          docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+#          docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+#
+#      - name: Download wheel
+#        uses: actions/download-artifact@v4
+#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#        with:
+#          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
+#          name: ${{ env.BUILD_IDENTIFIER }}.node
+#
+#      - name: Download wheel
+#        uses: actions/download-artifact@v4
+#        if: ${{ inputs.platform-tag == 'win_amd64' }}
+#        with:
+#          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-win32-x64/
+#          name: ${{ env.BUILD_IDENTIFIER }}.node
+#
+#      - name: Convert Python tag to Python version
+#        # Don't use sed because we want this command to work on both mac and windows
+#        # The command used in GNU sed is different than in macOS sed
+#        run: |
+#          NODEJS_TAG=${{ matrix.nodejs-tag[0] }}
+#          NODEJS_VERSION="${NODEJS_TAG/cp/}"
+#          echo NODEJS_VERSION="${NODEJS_VERSION/3/3.}" >> $GITHUB_ENV
+#        shell: bash
+#
+#      - uses: actions/setup-node@v4
+#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#        with:
+#          node-version: ${{ matrix.nodejs-tag[1] }}
+#          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
+#
+#      - uses: actions/setup-node@v4
+#        if: ${{ inputs.platform-tag == 'win_amd64' }}
+#        with:
+#          node-version: ${{ matrix.nodejs-tag[1] }}
+#          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-win32-x64/
+#
+#
+##      - name: Install nvm
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
+##          touch ~/.zprofile
+##          source ~/.zprofile
+##          nvm -v
+##        shell: bash
+##
+##      #- name: Install Node.js 20
+##      #  if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##      #  run: |
+##      #    nvm i 20
+##      #  shell: bash
+##
+##      - name: Prepare /usr/local/opt directory
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          sudo rm -rf /usr/local/opt
+##          sudo mkdir -p /usr/local/opt
+##          sudo chown -R $(whoami) /usr/local/opt
+##        shell: bash
+##
+##      - name: Install libuv
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          brew install libuv
+##          sudo ln -s /opt/homebrew/opt/libuv/1.45.0/ /usr/local/opt/libuv
+##        shell: bash
+##
+##      - name: Configure OpenSSL
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          rm -rf /usr/local/opt/openssl
+##          sudo ln -s /opt/homebrew/opt/openssl@3.4/ /usr/local/opt/openssl
+##        shell: bash
+##
+##      - name: Update PATH and environment variables
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          echo "export PATH=\"/usr/local/bin/:/usr/local/opt/openssl/bin:\$PATH\"" >> ~/.zprofile
+##          echo "export LDFLAGS=\"-L/usr/local/opt/openssl/lib\"" >> ~/.zprofile
+##          echo "export CPPFLAGS=\"-I/usr/local/opt/openssl/include\"" >> ~/.zprofile
+##          echo "export EXT_CFLAGS=\"-I/usr/local/opt/openssl/include\"" >> ~/.zprofile
+##        shell: bash
+##
+##      - name: Source updated environment variables
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          source ~/.zprofile
+##        shell: bash
+#
+##      - name: Install wheel
+##        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+##        run: |
+##          ./scripts/build-c-client.sh
+##          npm install
+##        shell: bash
+#
+##      - name: Install wheel
+##        if: ${{ inputs.platform-tag == 'win_amd64' }}
+##        run: |
+##          ./scripts/build-c-client.ps1
+##          npm install
+##        shell: powershell
+#
+#      - name: Connect to Docker container on remote machine with Docker daemon
+#        if: ${{ inputs.platform-tag == 'win_amd64' }}
+#        # DOCKER_HOST contains the IP address of the remote machine
+#        run: |
+#          $env:DOCKER_HOST_IP = $env:DOCKER_HOST | foreach {$_.replace("tcp://","")} | foreach {$_.replace(":2375", "")}
+#          crudini --set config.conf enterprise-edition hosts ${env:DOCKER_HOST_IP}:3000
+#        working-directory: .github\workflows
+#
+#      ## FIGURE OUT WHAT SETUP NEEDS TO HAPPEN
+#      #- run: |
+#      #    npm install typescript --save-dev
+#      #    npx tsc;
+#      #  working-directory: ts-test
+#      #  shell: bash
+#
+#      #- name: Identify binaries
+#      #  if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#      #  run: |
+#      #    ls ./lib/binding/node-v108-darwin-arm64
+#      #    ls ./lib/binding/node-v108-darwin-arm64/aerospike.node
+#      #    mkdir -p build;
+#      #    mkdir -p build/Release;
+#      #    cp -r ./lib/binding/node-v108-darwin-arm64 build/Release
+#
+#      - name: Run tests
+#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#        run: |
+#          docker ps;
+#          docker logs aerospike;
+#          cd ts-test;
+#          npm uninstall tsc;
+#          npm install ..;
+#          npm i --save-dev @types/chai;
+#          npm i --save-dev @types/jest;
+#          npm i --save-dev @types/mocha;
+#          npm install mocha;
+#          rm -rf dist;
+#          npx tsc;
+#          cd ..;
+#          npm install;
+#          pwd;
+#          npx tsc;
+#          npm run test dist/${{ inputs.test-file }} -- --h localhost --port 3000 --U superuser --P superuser;
+#
+#
+#      - name: Run tests
+#        if: ${{ inputs.platform-tag == 'win_amd64' }}
+#        run: |
+#          docker ps;
+#          docker logs aerospike;
+#          cd ts-test;
+#          npm uninstall tsc;
+#          npm install ..;
+#          npm i --save-dev @types/chai;
+#          npm i --save-dev @types/jest;
+#          npm i --save-dev @types/mocha;
+#          npm install mocha;
+#          npx tsc;
+#          cp tests\udf.lua dist\udf.lua;
+#          npx mocha dist -- --h ${env:DOCKER_HOST_IP} --port 3000 --U superuser --P superuser;
+#          cd ..; 
+#          npx tsc;
+#
+#
+#      - name: Show job status for commit
+#        if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+#        uses: myrotvorets/set-commit-status-action@v2.0.0
+#        with:
+#          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+#          status: ${{ job.status }}
+#          context: ${{ env.STATUS_CHECK_MESSAGE }}
+#
