Repairing action

diff --git a/.github/workflows/build-bindings.yml b/.github/workflows/build-bindings.yml
--- a/.github/workflows/build-bindings.yml
+++ b/.github/workflows/build-bindings.yml
@@ -181,33 +181,33 @@ jobs:
       if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
       uses: ./.github/actions/setup-docker-on-macos
 
-    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
-      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
-      uses: ./.github/actions/run-ee-server-for-ext-container
-      with:
-        use-server-rc: ${{ inputs.use-server-rc }}
-        server-tag: ${{ inputs.server-tag }}
-        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
-        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+    #- name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
+    #  if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+    #  uses: ./.github/actions/run-ee-server-for-ext-container
+    #  with:
+    #    use-server-rc: ${{ inputs.use-server-rc }}
+    #    server-tag: ${{ inputs.server-tag }}
+    #    docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+    #    docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
 
-    - name: Remove aerospike docker image
-      if: ${{ inputs.run_tests && inputs.platform-tag == 'manylinux_x86_64'}}
-      run: |
-        if docker ps -aq | grep -q .; then
-          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
-        else
-          echo "No containers to remove."
-        fi
+    #- name: Remove aerospike docker image
+    #  if: ${{ inputs.run_tests && inputs.platform-tag == 'manylinux_x86_64'}}
+    #  run: |
+    #    if docker ps -aq | grep -q .; then
+    #      docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+    #    else
+    #      echo "No containers to remove."
+    #    fi
 
-    # TODO: combine this composite action and the above into one
-    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
-      if: ${{ inputs.run_tests && inputs.platform-tag == 'manylinux_x86_64'}}
-      uses: ./.github/actions/run-ee-server-for-ext-container
-      with:
-        use-server-rc: ${{ inputs.use-server-rc }}
-        server-tag: ${{ inputs.server-tag }}
-        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
-        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+    ## TODO: combine this composite action and the above into one
+    #- name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
+    #  if: ${{ inputs.run_tests && inputs.platform-tag == 'manylinux_x86_64'}}
+    #  uses: ./.github/actions/run-ee-server-for-ext-container
+    #  with:
+    #    use-server-rc: ${{ inputs.use-server-rc }}
+    #    server-tag: ${{ inputs.server-tag }}
+    #    docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+    #    docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
 
     # FIND NO SERVER TESTS AND RUN THEM
     #
