CI/CD Improvement

diff --git a/.github/workflows/build-bindings.yml b/.github/workflows/build-bindings.yml
--- a/.github/workflows/build-bindings.yml
+++ b/.github/workflows/build-bindings.yml
@@ -206,7 +206,12 @@ jobs:
 
     - name: Remove aerospike docker image
       if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' && inputs.platform-tag == 'manylinux_aarch64' }}
-      run: docker ps -aq | grep -q . && docker rm -f $(docker ps -aq)
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
 
     # TODO: combine this composite action and the above into one
     - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
