Running stage tests

diff --git a/.github/workflows/stage-comprehensive-tests.yml b/.github/workflows/stage-comprehensive-tests.yml
--- a/.github/workflows/stage-comprehensive-tests.yml
+++ b/.github/workflows/stage-comprehensive-tests.yml
@@ -160,22 +160,126 @@ jobs:
         ls lib/binding;
       working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
 
+  test-pnpm:
+    needs: get-runner-os
+    if: ${{ inputs.run_tests && (inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'macosx_x86_64') }}
+    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
+      fail-fast: false
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+    steps:
+
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      with:
+        submodules: recursive
+        fetch-depth: 0
+
+    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
+      with: 
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: 'Windows: Install C client deps'
+      if: ${{ inputs.platform-tag == 'win_amd64' }}
+      run: nuget restore
+      working-directory: aerospike-client-c/vs
+
+    - name: 'macOS x86: Setup Docker using colima for testing'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/setup-docker-on-macos
+
+    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.soup_hat }}
+        docker-hub-password: ${{ secrets.cell_girl }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    # TODO: combine this composite action and the above into one
+    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
+      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.soup_hat }}
+        docker-hub-password: ${{ secrets.cell_girl }}
+
+
+    - name: Set up JFrog credentials
+      uses: jfrog/setup-jfrog-cli@88e9eba31c07e31beefa4cef5c0e93d1af9535d7 # v4.6.1
+      env:
+        JF_URL: https://aerospike.jfrog.io
+      with:
+        oidc-provider-name: gh-aerospike-clients
+        oidc-audience: aerospike/clients
+
+    - name: Download Artifacts from Jfrog
+      run: jf rt dl "clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/" "downloaded-artifacts/"
+      env:
+        NEW_VERSION: ${{ inputs.version }}
+        PACKAGE_MANAGER: npm
+
+    - name: list Artifacts
+      run: |
+        ls downloaded-artifacts
+        ls downloaded-artifacts/aerospike
+        ls downloaded-artifacts/aerospike/${{ env.NEW_VERSION }}
+      env:
+        NEW_VERSION: ${{ inputs.version }}
+
+    - name: Move artifacts
+      run: |
+        tar --strip-components=1 -xvf aerospike-${{ env.NEW_VERSION }}.tgz
+      env:
+        NEW_VERSION: ${{ inputs.version }}
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
+
+    - name: check binding
+      run:
+        ls lib/binding;
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
 
 
     - name: Run tests
       if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux')}}
       run: |
-        docker ps;
-        docker logs aerospike;
-        cp ../../../package-lock.json package-lock.json;
-        npm ci --ignore-scripts;
-        cd ts-test;
-        npm ci .. --ignore-scripts;
-        npx tsc;
-        cd ..;
-        rm -rf ts-test/dist;
-        npx tsc;
-        npm run test -- --t 40000 --h 127.0.0.1 --port 3000 --U superuser --P superuser;
+      docker ps
+      docker logs aerospike
+      cp ../../../package-lock.json package-lock.json
+      npm install -g pnpm
+      pnpm install --frozen-lockfile --ignore-scripts
+      cd ts-test
+      pnpm install --frozen-lockfile --ignore-scripts ..
+      pnpm exec tsc
+      cd ..
+      rm -rf ts-test/dist
+      pnpm exec tsc
+      pnpm run test -- --t 40000 --h 127.0.0.1 --port 3000 --U superuser --P superuser
       working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
 
     - name: Run tests
@@ -190,6 +294,176 @@ jobs:
         npx tsc;
         cd ..;
         npx tsc;
+        npm run test -- --t 40000 --h 127.0.0.1 --port 3000 --U superuser --P superuser;
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && (inputs.platform-tag == 'macosx_arm64' ) }}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cp ../../../package-lock.json package-lock.json;
+        npm ci --ignore-scripts;
+        cd ts-test;
+        npm ci .. --ignore-scripts;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test -- --t 40000 --h 127.0.0.1 --port 3000 --U superuser --P superuser;
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
+
+    #- name: Debug server
+    #  run: |
+    #    docker ps;
+    #    docker logs aerospike;
+
+
+    - name: Set final commit status
+      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
+      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        status: ${{ job.status }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+  test-bun:
+    needs: get-runner-os
+    if: ${{ inputs.run_tests && (inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'macosx_x86_64') }}
+    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
+      fail-fast: false
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+    steps:
+
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # 2.0.1
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      with:
+        submodules: recursive
+        fetch-depth: 0
+
+    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
+      with: 
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: 'Windows: Install C client deps'
+      if: ${{ inputs.platform-tag == 'win_amd64' }}
+      run: nuget restore
+      working-directory: aerospike-client-c/vs
+
+    - name: 'macOS x86: Setup Docker using colima for testing'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/setup-docker-on-macos
+
+    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.soup_hat }}
+        docker-hub-password: ${{ secrets.cell_girl }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    # TODO: combine this composite action and the above into one
+    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
+      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.soup_hat }}
+        docker-hub-password: ${{ secrets.cell_girl }}
+
+
+    - name: Set up JFrog credentials
+      uses: jfrog/setup-jfrog-cli@88e9eba31c07e31beefa4cef5c0e93d1af9535d7 # v4.6.1
+      env:
+        JF_URL: https://aerospike.jfrog.io
+      with:
+        oidc-provider-name: gh-aerospike-clients
+        oidc-audience: aerospike/clients
+
+    - name: Download Artifacts from Jfrog
+      run: jf rt dl "clients-npm-dev-local/aerospike/${{ env.NEW_VERSION }}/" "downloaded-artifacts/"
+      env:
+        NEW_VERSION: ${{ inputs.version }}
+        PACKAGE_MANAGER: npm
+
+    - name: list Artifacts
+      run: |
+        ls downloaded-artifacts
+        ls downloaded-artifacts/aerospike
+        ls downloaded-artifacts/aerospike/${{ env.NEW_VERSION }}
+      env:
+        NEW_VERSION: ${{ inputs.version }}
+
+    - name: Move artifacts
+      run: |
+        tar --strip-components=1 -xvf aerospike-${{ env.NEW_VERSION }}.tgz
+      env:
+        NEW_VERSION: ${{ inputs.version }}
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
+
+    - name: check binding
+      run:
+        ls lib/binding;
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
+
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux')}}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cp ../../../package-lock.json package-lock.json;
+        curl -fsSL https://bun.sh/install | bash;
+        export PATH="$HOME/.bun/bin:$PATH";
+        bun ci --ignore-scripts;
+        cd ts-test;
+        bun ci .. --ignore-scripts;
+        npx tsc;
+        cd ..;
+        rm -rf ts-test/dist;
+        bunx tsc;
+        npm run test -- --t 40000 --h 127.0.0.1 --port 3000 --U superuser --P superuser;
+      working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && (inputs.platform-tag != 'macosx_arm64' && inputs.platform-tag != 'macosx_x86_64') }}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cp ../../../package-lock.json package-lock.json;
+        curl -fsSL https://bun.sh/install | bash;
+        export PATH="$HOME/.bun/bin:$PATH";
+        bun ci --ignore-scripts;
+        cd ts-test;
+        bun ci .. --ignore-scripts;
+        npx tsc;
+        cd ..;
+        rm -rf ts-test/dist;
+        bunx tsc;
         npm run test -- --t 40000 --h 127.0.0.1 --port 3000 --U superuser --P superuser;
       working-directory: downloaded-artifacts/aerospike/${{ inputs.version }}
 
