PIPELINE IMPROVMENTS

diff --git a/.github/workflows/test-dev-artifacts.yml b/.github/workflows/test-dev-artifacts.yml
--- a/.github/workflows/test-dev-artifacts.yml
+++ b/.github/workflows/test-dev-artifacts.yml
@@ -127,7 +127,7 @@ jobs:
       shell: bash
 
 
-  cibuildbinding:
+  build-and-test-ee:
     needs: get-runner-os
     strategy:
       matrix:
@@ -138,6 +138,8 @@ jobs:
       BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
       MACOS_OPENSSL_VERSION: 3
     steps:
+
+    # REUSABLE PART
     - name: Create status check message
       run: echo STATUS_CHECK_MESSAGE="cibuildbinding (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
       shell: bash
@@ -290,7 +292,250 @@ jobs:
         status: ${{ job.status }}
         context: ${{ env.STATUS_CHECK_MESSAGE }}
 
-  test-self-hosted:
+  test-ce:
+    needs: get-runner-os
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
+      fail-fast: false
+    runs-on: ${{ startsWith(inputs.platform-tag, 'manylinux') }}
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+      MACOS_OPENSSL_VERSION: 3
+    steps:
+
+    # REUSABLE PART
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="cibuildbinding (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@v4
+      with:
+        submodules: recursive
+        ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        # We need the last tag before the ref, so we can relabel the version if needed
+        fetch-depth: 0
+
+    - uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    - name: Run latest Community edition Aerospike server
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
+      run: docker run -d --network=host --name aerospike -p 3000-3002:3000-3002 aerospike/aerospike-server
+
+    # FIND NO SERVER TESTS AND RUN THEM
+    #
+    #- name: If not running tests against server, only run basic import test
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'false' }}
+    #  # Use double quotes otherwise Windows will throw this error in cibuildwheel
+    #  # 'import
+    #  #       ^
+    #  # SyntaxError: EOL while scanning string literal
+    #  run: echo "TEST_COMMAND=python -c \"import aerospike\"" >> $GITHUB_ENV
+    #  shell: bash
+
+    #- name: Otherwise, enable integration tests
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' }}
+    #  run: echo "TEST_COMMAND=cd ts-test;
+    #    npm install typescript --save-dev;
+    #    npx tsc;
+    #    cd ..;
+    #    npm run test dist/ -- --h 127.0.0.1 --port 3000" >> $GITHUB_ENV
+    #  shell: bash
+
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: nodejs-client-artifacts
+        path: ./downloaded-artifacts
+
+    - name: list Artifacts first
+      run: |
+        ls ./downloaded-artifacts
+        ls ./downloaded-artifacts/glibc@2.31
+        ls ./downloaded-artifacts/glibc@2.35
+
+    - name: Move artifacts
+      run: |
+        mkdir -p lib/binding
+        cp -r downloaded-artifacts/* lib/binding
+
+
+    - name: Delete leftover artifacts
+      if: ${{ !(inputs.platform-tag == 'win_amd64') }}
+      run: |
+        rm -rf downloaded-artifacts/
+
+    - name: check binding
+      run:
+        ls lib/binding;
+        ls lib/binding/glibc@2.35;
+        ls lib/binding/glibc@2.31;
+
+    - name: Change install command for release
+      run: node ./scripts/change-install-command.js
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cd ts-test;
+        npm install;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test dist/${{ inputs.test-file }} -- --h 172.17.0.2 --port 3000 --U superuser --P superuser;
+
+    - name: Set final commit status
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        status: ${{ job.status }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+  test-lowest-supported-server:
+    needs: get-runner-os
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
+      fail-fast: false
+    runs-on: ${{ startsWith(inputs.platform-tag, 'manylinux') }}
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+      MACOS_OPENSSL_VERSION: 3
+    steps:
+
+    # REUSABLE PART
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="cibuildbinding (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@v4
+      with:
+        submodules: recursive
+        ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        # We need the last tag before the ref, so we can relabel the version if needed
+        fetch-depth: 0
+
+    - uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    - name: Run lowest supported server
+      run: |
+        SERVER_VERSION=$(curl -s "https://registry.hub.docker.com/v2/repositories/aerospike/aerospike-server/tags?page_size=100" | jq '.results[] | select(.name | startswith("6.1")).name' -r | head -n 1)
+        docker run -d --name aerospike -p 3000-3002:3000-3002 aerospike/aerospike-server:$SERVER_VERSION
+
+    # FIND NO SERVER TESTS AND RUN THEM
+    #
+    #- name: If not running tests against server, only run basic import test
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'false' }}
+    #  # Use double quotes otherwise Windows will throw this error in cibuildwheel
+    #  # 'import
+    #  #       ^
+    #  # SyntaxError: EOL while scanning string literal
+    #  run: echo "TEST_COMMAND=python -c \"import aerospike\"" >> $GITHUB_ENV
+    #  shell: bash
+
+    #- name: Otherwise, enable integration tests
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' }}
+    #  run: echo "TEST_COMMAND=cd ts-test;
+    #    npm install typescript --save-dev;
+    #    npx tsc;
+    #    cd ..;
+    #    npm run test dist/ -- --h 127.0.0.1 --port 3000" >> $GITHUB_ENV
+    #  shell: bash
+
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: nodejs-client-artifacts
+        path: ./downloaded-artifacts
+
+    - name: list Artifacts first
+      run: |
+        ls ./downloaded-artifacts
+        ls ./downloaded-artifacts/glibc@2.31
+        ls ./downloaded-artifacts/glibc@2.35
+
+    - name: Move artifacts
+      run: |
+        mkdir -p lib/binding
+        cp -r downloaded-artifacts/* lib/binding
+
+
+    - name: Delete leftover artifacts
+      if: ${{ !(inputs.platform-tag == 'win_amd64') }}
+      run: |
+        rm -rf downloaded-artifacts/
+
+    - name: check binding
+      run:
+        ls lib/binding;
+        ls lib/binding/glibc@2.35;
+        ls lib/binding/glibc@2.31;
+
+    - name: Change install command for release
+      run: node ./scripts/change-install-command.js
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cd ts-test;
+        npm install;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test dist/${{ inputs.test-file }} -- --h 172.17.0.2 --port 3000 --U superuser --P superuser;
+
+    - name: Set final commit status
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        status: ${{ job.status }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+  test-self-hosted-ee:
     needs: cibuildbinding
     # There's a top-level env variable for this but we can't use it here, unfortunately
     if: ${{ inputs.run_tests && (inputs.platform-tag == 'macosx_arm64' || inputs.platform-tag == 'win_amd64') }}
@@ -436,120 +681,119 @@ jobs:
           status: ${{ job.status }}
           context: ${{ env.STATUS_CHECK_MESSAGE }}
 
-  valgrind-self-hosted:
-    needs: cibuildbinding
-    # There's a top-level env variable for this but we can't use it here, unfortunately
-    strategy:
-      fail-fast: false
-    runs-on: ${{ fromJSON('["self-hosted", "macOS", "ARM64", "SMA"]') }}
-    env:
-      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
-    steps:
-      # REUSABLE SECTION
-      - name: Create status check message
-        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
-        shell: bash
-
-      - name: Show job status for commit
-        uses: myrotvorets/set-commit-status-action@v2.0.0
-        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
-        with:
-          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-          context: ${{ env.STATUS_CHECK_MESSAGE }}
-
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-
-      # Need to be able to save Docker Hub credentials to keychain
-      - if: ${{ inputs.platform-tag == 'macosx_arm64' && inputs.use-server-rc }}
-        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
-
-      - name: Remove aerospike docker image
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        run: |
-          if docker ps -aq | grep -q .; then
-            docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
-          else
-            echo "No containers to remove."
-          fi
-
-      - uses: ./.github/actions/run-ee-server
-        with:
-          use-server-rc: ${{ inputs.use-server-rc }}
-          server-tag: ${{ inputs.server-tag }}
-          docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
-          docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
-
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: nodejs-client-artifacts
-          path: ./downloaded-artifacts
-
-      - name: list Artifacts first
-        run: |
-          ls ./downloaded-artifacts
-          ls ./downloaded-artifacts/glibc@2.31
-          ls ./downloaded-artifacts/glibc@2.35
-
-      - name: Move artifacts
-        run: |
-          mkdir -p lib/binding
-          cp -r downloaded-artifacts/* lib/binding
-
-
-      - name: Delete leftover artifacts
-        if: ${{ !(inputs.platform-tag == 'win_amd64') }}
-        run: |
-          rm -rf downloaded-artifacts/
-
-      - name: check binding
-        run: |
-          ls lib/binding;
-          ls lib/binding/glibc@2.35;
-          ls lib/binding/glibc@2.31;
-
-          
-      #- name: Change install command for release
-      #  run: node ./scripts/change-install-command.js
-
-      #- name: npm install
-      #  run: npm install
-
-      - uses: actions/setup-node@v4
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        with:
-          node-version: ${{ matrix.nodejs-tag[1] }}
-          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
-
-      - name: install valgrind
-        run: |
-          sudo apt-get update;
-          sudo apt update;
-          sudo apt install valgrind;
-
-      # REUSABLE SECTION 
-
-      - name: Run tests
-        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
-        run: |
-          docker ps;
-          docker logs aerospike;
-          cd ts-test;
-          npm install;
-          npx tsc;
-          cd ..;
-          npx tsc;
-          npm run valgrind -- --t 40000
-
-      - name: Show job status for commit
-        if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
-        uses: myrotvorets/set-commit-status-action@v2.0.0
-        with:
-          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-          status: ${{ job.status }}
-          context: ${{ env.STATUS_CHECK_MESSAGE }}
+#  valgrind-self-hosted:
+#    needs: cibuildbinding
+#    # There's a top-level env variable for this but we can't use it here, unfortunately
+#    strategy:
+#      fail-fast: false
+#    runs-on: ${{ fromJSON('["self-hosted", "macOS", "ARM64", "SMA"]') }}
+#    env:
+#      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+#    steps:
+#      # REUSABLE SECTION
+#      - name: Create status check message
+#        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+#        shell: bash
+#
+#      - name: Show job status for commit
+#        uses: myrotvorets/set-commit-status-action@v2.0.0
+#        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+#        with:
+#          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+#          context: ${{ env.STATUS_CHECK_MESSAGE }}
+#
+#      - uses: actions/checkout@v4
+#        with:
+#          ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+#
+#      # Need to be able to save Docker Hub credentials to keychain
+#      - if: ${{ inputs.platform-tag == 'macosx_arm64' && inputs.use-server-rc }}
+#        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
+#
+#      - name: Remove aerospike docker image
+#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#        run: |
+#          if docker ps -aq | grep -q .; then
+#            docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+#          else
+#            echo "No containers to remove."
+#          fi
+#
+#      - uses: ./.github/actions/run-ee-server
+#        with:
+#          use-server-rc: ${{ inputs.use-server-rc }}
+#          server-tag: ${{ inputs.server-tag }}
+#          docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+#          docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+#
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: nodejs-client-artifacts
+#          path: ./downloaded-artifacts
+#
+#      - name: list Artifacts first
+#        run: |
+#          ls ./downloaded-artifacts
+#          ls ./downloaded-artifacts/glibc@2.31
+#          ls ./downloaded-artifacts/glibc@2.35
+#
+#      - name: Move artifacts
+#        run: |
+#          mkdir -p lib/binding
+#          cp -r downloaded-artifacts/* lib/binding
+#
+#
+#      - name: Delete leftover artifacts
+#        if: ${{ !(inputs.platform-tag == 'win_amd64') }}
+#        run: |
+#          rm -rf downloaded-artifacts/
+#
+#      - name: check binding
+#        run: |
+#          ls lib/binding;
+#          ls lib/binding/glibc@2.35;
+#          ls lib/binding/glibc@2.31;
+#
+#          
+#      #- name: Change install command for release
+#      #  run: node ./scripts/change-install-command.js
+#
+#      #- name: npm install
+#      #  run: npm install
+#
+#      - uses: actions/setup-node@v4
+#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#        with:
+#          node-version: ${{ matrix.nodejs-tag[1] }}
+#          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
+#
+#      - name: install valgrind
+#        run: |
+#          brew install valgrind
+#
+#
+#      # REUSABLE SECTION 
+#
+#      - name: Run tests
+#        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+#        run: |
+#          docker ps;
+#          docker logs aerospike;
+#          cd ts-test;
+#          npm install;
+#          npx tsc;
+#          cd ..;
+#          npx tsc;
+#          npm run valgrind -- --t 40000
+#
+#      - name: Show job status for commit
+#        if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+#        uses: myrotvorets/set-commit-status-action@v2.0.0
+#        with:
+#          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+#          status: ${{ job.status }}
+#          context: ${{ env.STATUS_CHECK_MESSAGE }}
 
 
 
@@ -656,7 +900,7 @@ jobs:
         # DOCKER_HOST contains the IP address of the remote machine
         run: |
           $env:DOCKER_HOST_IP = $env:DOCKER_HOST | foreach {$_.replace("tcp://","")} | foreach {$_.replace(":2375", "")}
-        #  crudini --set config.conf enterprise-edition hosts ${env:DOCKER_HOST_IP}:3000
+          crudini --set config.conf community-edition hosts ${env:DOCKER_HOST_IP}:3000
         working-directory: .github\workflows
 
       # REUSABLE SECTION 
