PIPELINE IMPROVMENTS

diff --git a/.github/workflows/test-dev-artifacts.yml b/.github/workflows/test-dev-artifacts.yml
--- a/.github/workflows/test-dev-artifacts.yml
+++ b/.github/workflows/test-dev-artifacts.yml
@@ -292,6 +292,196 @@ jobs:
         status: ${{ job.status }}
         context: ${{ env.STATUS_CHECK_MESSAGE }}
 
+  test-tsc-compile:
+    needs: get-runner-os
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON('[["v131", "23"]]') }}
+      fail-fast: false
+    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+      MACOS_OPENSSL_VERSION: 3
+    steps:
+
+    # REUSABLE PART
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@v4
+      with:
+        submodules: recursive
+        ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        # We need the last tag before the ref, so we can relabel the version if needed
+        fetch-depth: 0
+
+    - uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
+      run: |
+        npx tsc;
+        npx tsc typings/index.d.ts;
+        cd ts-test;
+        npx tsc;
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && inputs.platform-tag == 'macosx_x86_64'}}
+      run: |
+          npx tsc;
+          npx tsc typings/index.d.ts;
+          cd ts-test;
+          npx tsc;
+
+    - name: Set final commit status
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        status: ${{ job.status }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+  test-metrics:
+    needs: get-runner-os
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON('[["v131", "23"]]') }}
+      fail-fast: false
+    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+      MACOS_OPENSSL_VERSION: 3
+    steps:
+
+    # REUSABLE PART
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@v4
+      with:
+        submodules: recursive
+        ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        # We need the last tag before the ref, so we can relabel the version if needed
+        fetch-depth: 0
+
+    - uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    # FIND NO SERVER TESTS AND RUN THEM
+    #
+    #- name: If not running tests against server, only run basic import test
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'false' }}
+    #  # Use double quotes otherwise Windows will throw this error in cibuildwheel
+    #  # 'import
+    #  #       ^
+    #  # SyntaxError: EOL while scanning string literal
+    #  run: echo "TEST_COMMAND=python -c \"import aerospike\"" >> $GITHUB_ENV
+    #  shell: bash
+
+    #- name: Otherwise, enable integration tests
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' }}
+    #  run: echo "TEST_COMMAND=cd ts-test;
+    #    npm install typescript --save-dev;
+    #    npx tsc;
+    #    cd ..;
+    #    npm run test dist/ -- --h 127.0.0.1 --port 3000" >> $GITHUB_ENV
+    #  shell: bash
+
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: nodejs-client-artifacts
+        path: ./downloaded-artifacts
+
+    - name: list Artifacts first
+      run: |
+        ls ./downloaded-artifacts
+        ls ./downloaded-artifacts/glibc@2.31
+        ls ./downloaded-artifacts/glibc@2.35
+
+    - name: Move artifacts
+      run: |
+        mkdir -p lib/binding
+        cp -r downloaded-artifacts/* lib/binding
+
+
+    - name: Delete leftover artifacts
+      if: ${{ !(inputs.platform-tag == 'win_amd64') }}
+      run: |
+        rm -rf downloaded-artifacts/
+
+    - name: check binding
+      run:
+        ls lib/binding;
+        ls lib/binding/glibc@2.35;
+        ls lib/binding/glibc@2.31;
+
+    - name: Change install command for release
+      run: node ./scripts/change-install-command.js
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cd ts-test;
+        npm install;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test dist/metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+        npm run test dist/metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && inputs.platform-tag == 'macosx_x86_64'}}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cd ts-test;
+        npm install;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test dist/metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+        npm run test dist/metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+
+    - name: Set final commit status
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        status: ${{ job.status }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
   test-ce:
     needs: get-runner-os
     strategy:
@@ -670,6 +860,71 @@ jobs:
           cd ..;
           npx tsc;
           npm run test dist/${{ inputs.test-file }} -- --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+
+
+      - name: Show job status for commit
+        if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+        uses: myrotvorets/set-commit-status-action@v2.0.0
+        with:
+          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+          status: ${{ job.status }}
+          context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+  test-tsc-compile-self-hosted:
+    # There's a top-level env variable for this but we can't use it here, unfortunately
+    if: ${{ inputs.run_tests && (inputs.platform-tag == 'macosx_arm64' || inputs.platform-tag == 'win_amd64') }}
+    strategy:
+      fail-fast: false
+      matrix:
+        nodejs-tag: ${{ fromJSON('[["v131", "23"]]') }}
+    runs-on: ${{ inputs.platform-tag == 'macosx_arm64' && fromJSON('["self-hosted", "macOS", "ARM64", "SMA"]') || fromJSON('["self-hosted", "Windows", "X64"]') }}
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+    steps:
+
+      # REUSABLE SECTION
+      - name: Create status check message
+        run: echo STATUS_CHECK_MESSAGE="Test on self hosted (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Show job status for commit
+        uses: myrotvorets/set-commit-status-action@v2.0.0
+        if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+        with:
+          sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+          context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+
+      # Need to be able to save Docker Hub credentials to keychain
+      - if: ${{ inputs.platform-tag == 'macosx_arm64' && inputs.use-server-rc }}
+        run: security unlock-keychain -p ${{ secrets.MAC_M1_SELF_HOSTED_RUNNER_PW }}
+
+      - uses: actions/setup-node@v4
+        #if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+        with:
+          node-version: ${{ matrix.nodejs-tag[1] }}
+          path: ./lib/binding/node-${{ matrix.nodejs-tag[0] }}-darwin-arm64/
+
+      # REUSABLE SECTION 
+
+      - name: Run tests
+        if: ${{ inputs.platform-tag == 'win_amd64' }}
+        run: |
+          npx tsc;
+          npx tsc typings/index.d.ts;
+          cd ts-test;
+          npx tsc;
+
+      - name: Run tests
+        if: ${{ inputs.platform-tag == 'macosx_arm64' }}
+        run: |
+          npx tsc;
+          npx tsc typings/index.d.ts;
+          cd ts-test;
+          npx tsc;
 
 
       - name: Show job status for commit
