PIPELINE IMPROVMENTS

diff --git a/.github/workflows/test-dev-artifacts.yml b/.github/workflows/test-dev-artifacts.yml
--- a/.github/workflows/test-dev-artifacts.yml
+++ b/.github/workflows/test-dev-artifacts.yml
@@ -304,6 +304,7 @@ jobs:
       MACOS_OPENSSL_VERSION: 3
     steps:
 
+
     # REUSABLE PART
     - name: Create status check message
       run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
@@ -326,6 +327,104 @@ jobs:
     - uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: print conditional values
+      run: |
+        echo "Platform tag: '${{ inputs.platform-tag }}'"
+        echo "Platform conditional: '${{ inputs.platform-tag == 'win_amd64' }}'"
+        echo "Platform conditional: 'if: ${{ inputs.platform-tag == 'macosx_x86_64' }}'"
+        echo "Platform conditional: 'runs-on: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}'"
+        echo "Platform conditional: '${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}'"
+
+    - name: 'Windows: Install C client deps'
+      if: ${{ inputs.platform-tag == 'win_amd64' }}
+      run: nuget restore
+      working-directory: aerospike-client-c/vs
+
+    - name: 'macOS x86: Setup Docker using colima for testing'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/setup-docker-on-macos
+
+    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    # TODO: combine this composite action and the above into one
+    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
+      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+
+    # FIND NO SERVER TESTS AND RUN THEM
+    #
+    #- name: If not running tests against server, only run basic import test
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'false' }}
+    #  # Use double quotes otherwise Windows will throw this error in cibuildwheel
+    #  # 'import
+    #  #       ^
+    #  # SyntaxError: EOL while scanning string literal
+    #  run: echo "TEST_COMMAND=python -c \"import aerospike\"" >> $GITHUB_ENV
+    #  shell: bash
+
+    #- name: Otherwise, enable integration tests
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' }}
+    #  run: echo "TEST_COMMAND=cd ts-test;
+    #    npm install typescript --save-dev;
+    #    npx tsc;
+    #    cd ..;
+    #    npm run test dist/ -- --h 127.0.0.1 --port 3000" >> $GITHUB_ENV
+    #  shell: bash
+
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: nodejs-client-artifacts
+        path: ./downloaded-artifacts
+
+    - name: list Artifacts first
+      run: |
+        ls ./downloaded-artifacts
+        ls ./downloaded-artifacts/glibc@2.31
+        ls ./downloaded-artifacts/glibc@2.35
+
+    - name: Move artifacts
+      run: |
+        mkdir -p lib/binding
+        cp -r downloaded-artifacts/* lib/binding
+
+
+    - name: Delete leftover artifacts
+      if: ${{ !(inputs.platform-tag == 'win_amd64') }}
+      run: |
+        rm -rf downloaded-artifacts/
+
+    - name: check binding
+      run:
+        ls lib/binding;
+        ls lib/binding/glibc@2.35;
+        ls lib/binding/glibc@2.31;
+
+    - name: Change install command for release
+      run: node ./scripts/change-install-command.js
 
     - name: Run tests
       if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
