PIPELINE IMPROVMENTS

diff --git a/.github/workflows/test-dev-artifacts.yml b/.github/workflows/test-dev-artifacts.yml
--- a/.github/workflows/test-dev-artifacts.yml
+++ b/.github/workflows/test-dev-artifacts.yml
@@ -572,172 +572,172 @@ jobs:
         status: ${{ job.status }}
         context: ${{ env.STATUS_CHECK_MESSAGE }}
 
-#  test-metrics:
-#    needs: get-runner-os
-#    strategy:
-#      matrix:
-#        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
-#      fail-fast: false
-#    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
-#    env:
-#      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
-#      MACOS_OPENSSL_VERSION: 3
-#    steps:
-#
-#    # REUSABLE PART
-#    - name: Create status check message
-#      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
-#      shell: bash
-#
-#    - name: Show job status for commit
-#      uses: myrotvorets/set-commit-status-action@v2.0.0
-#      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
-#      with:
-#        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-#        context: ${{ env.STATUS_CHECK_MESSAGE }}
-#
-#    - uses: actions/checkout@v4
-#      with:
-#        submodules: recursive
-#        ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-#        # We need the last tag before the ref, so we can relabel the version if needed
-#        fetch-depth: 0
-#
-#    - uses: actions/setup-node@v4
-#      with:
-#        node-version: ${{ matrix.nodejs-tag[1] }}
-#
-#    - name: print conditional values
-#      run: |
-#        echo "Platform tag: '${{ inputs.platform-tag }}'"
-#        echo "Platform conditional: '${{ inputs.platform-tag == 'win_amd64' }}'"
-#        echo "Platform conditional: 'if: ${{ inputs.platform-tag == 'macosx_x86_64' }}'"
-#        echo "Platform conditional: 'runs-on: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}'"
-#        echo "Platform conditional: '${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}'"
-#
-#    - name: 'Windows: Install C client deps'
-#      if: ${{ inputs.platform-tag == 'win_amd64' }}
-#      run: nuget restore
-#      working-directory: aerospike-client-c/vs
-#
-#    - name: 'macOS x86: Setup Docker using colima for testing'
-#      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
-#      uses: ./.github/actions/setup-docker-on-macos
-#
-#    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
-#      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
-#      uses: ./.github/actions/run-ee-server-for-ext-container
-#      with:
-#        use-server-rc: ${{ inputs.use-server-rc }}
-#        server-tag: ${{ inputs.server-tag }}
-#        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
-#        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
-#
-#    - name: Remove aerospike docker image
-#      if: ${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
-#      run: |
-#        if docker ps -aq | grep -q .; then
-#          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
-#        else
-#          echo "No containers to remove."
-#        fi
-#
-#    # TODO: combine this composite action and the above into one
-#    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
-#      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
-#      uses: ./.github/actions/run-ee-server-for-ext-container
-#      with:
-#        use-server-rc: ${{ inputs.use-server-rc }}
-#        server-tag: ${{ inputs.server-tag }}
-#        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
-#        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
-#
-#    # FIND NO SERVER TESTS AND RUN THEM
-#    #
-#    #- name: If not running tests against server, only run basic import test
-#    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'false' }}
-#    #  # Use double quotes otherwise Windows will throw this error in cibuildwheel
-#    #  # 'import
-#    #  #       ^
-#    #  # SyntaxError: EOL while scanning string literal
-#    #  run: echo "TEST_COMMAND=python -c \"import aerospike\"" >> $GITHUB_ENV
-#    #  shell: bash
-#
-#    #- name: Otherwise, enable integration tests
-#    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' }}
-#    #  run: echo "TEST_COMMAND=cd ts-test;
-#    #    npm install typescript --save-dev;
-#    #    npx tsc;
-#    #    cd ..;
-#    #    npm run test dist/ -- --h 127.0.0.1 --port 3000" >> $GITHUB_ENV
-#    #  shell: bash
-#
-#
-#    - name: Download artifacts
-#      uses: actions/download-artifact@v4
-#      with:
-#        name: nodejs-client-artifacts
-#        path: ./downloaded-artifacts
-#
-#    - name: list Artifacts first
-#      run: |
-#        ls ./downloaded-artifacts
-#        ls ./downloaded-artifacts/glibc@2.31
-#        ls ./downloaded-artifacts/glibc@2.35
-#
-#    - name: Move artifacts
-#      run: |
-#        mkdir -p lib/binding
-#        cp -r downloaded-artifacts/* lib/binding
-#
-#
-#    - name: Delete leftover artifacts
-#      if: ${{ !(inputs.platform-tag == 'win_amd64') }}
-#      run: |
-#        rm -rf downloaded-artifacts/
-#
-#    - name: check binding
-#      run:
-#        ls lib/binding;
-#        ls lib/binding/glibc@2.35;
-#        ls lib/binding/glibc@2.31;
-#
-#    - name: Change install command for release
-#      run: node ./scripts/change-install-command.js
-#
-#    - name: Run tests
-#      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
-#      run: |
-#        docker ps;
-#        docker logs aerospike;
-#        cd ts-test;
-#        npm install;
-#        npx tsc;
-#        cd ..;
-#        npx tsc;
-#        npm run test dist/metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
-#        npm run test dist/metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
-#
-#    - name: Run tests
-#      if: ${{ inputs.run_tests && inputs.platform-tag == 'macosx_x86_64'}}
-#      run: |
-#        docker ps;
-#        docker logs aerospike;
-#        cd ts-test;
-#        npm install;
-#        npx tsc;
-#        cd ..;
-#        npx tsc;
-#        npm run test dist/metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
-#        npm run test dist/metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
-#
-#    - name: Set final commit status
-#      uses: myrotvorets/set-commit-status-action@v2.0.0
-#      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
-#      with:
-#        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
-#        status: ${{ job.status }}
-#        context: ${{ env.STATUS_CHECK_MESSAGE }}
+  test-metrics:
+    needs: get-runner-os
+    strategy:
+      matrix:
+        nodejs-tag: ${{ fromJSON(inputs.nodejs-tags) }}
+      fail-fast: false
+    runs-on: ${{ needs.get-runner-os.outputs.runner-os }}
+    env:
+      BUILD_IDENTIFIER: "${{ matrix.nodejs-tag[0] }}-${{ inputs.platform-tag }}"
+      MACOS_OPENSSL_VERSION: 3
+    steps:
+
+    # REUSABLE PART
+    - name: Create status check message
+      run: echo STATUS_CHECK_MESSAGE="test-ee (${{ env.BUILD_IDENTIFIER }})" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Show job status for commit
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
+
+    - uses: actions/checkout@v4
+      with:
+        submodules: recursive
+        ref: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        # We need the last tag before the ref, so we can relabel the version if needed
+        fetch-depth: 0
+
+    - uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.nodejs-tag[1] }}
+
+    - name: print conditional values
+      run: |
+        echo "Platform tag: '${{ inputs.platform-tag }}'"
+        echo "Platform conditional: '${{ inputs.platform-tag == 'win_amd64' }}'"
+        echo "Platform conditional: 'if: ${{ inputs.platform-tag == 'macosx_x86_64' }}'"
+        echo "Platform conditional: 'runs-on: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}'"
+        echo "Platform conditional: '${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}'"
+
+    - name: 'Windows: Install C client deps'
+      if: ${{ inputs.platform-tag == 'win_amd64' }}
+      run: nuget restore
+      working-directory: aerospike-client-c/vs
+
+    - name: 'macOS x86: Setup Docker using colima for testing'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/setup-docker-on-macos
+
+    - name: 'macOS x86: run Aerospike server in Docker container and connect via localhost'
+      if: ${{ inputs.platform-tag == 'macosx_x86_64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+
+    - name: Remove aerospike docker image
+      if: ${{ inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      run: |
+        if docker ps -aq | grep -q .; then
+          docker rm -f $(docker ps -aq) || echo "Failed to remove one or more containers."
+        else
+          echo "No containers to remove."
+        fi
+
+    # TODO: combine this composite action and the above into one
+    - name: "Linux: run Aerospike server in Docker container and configure config.conf to connect to the server container's Docker IP address"
+      if: ${{ inputs.platform-tag == 'manylinux_x86_64' || inputs.platform-tag == 'manylinux_aarch64' || inputs.platform-tag == 'manylinux_20_x86_64' || inputs.platform-tag == 'manylinux_20_aarch64' }}
+      uses: ./.github/actions/run-ee-server-for-ext-container
+      with:
+        use-server-rc: ${{ inputs.use-server-rc }}
+        server-tag: ${{ inputs.server-tag }}
+        docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
+        docker-hub-password: ${{ secrets.DOCKER_HUB_BOT_PW }}
+
+    # FIND NO SERVER TESTS AND RUN THEM
+    #
+    #- name: If not running tests against server, only run basic import test
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'false' }}
+    #  # Use double quotes otherwise Windows will throw this error in cibuildwheel
+    #  # 'import
+    #  #       ^
+    #  # SyntaxError: EOL while scanning string literal
+    #  run: echo "TEST_COMMAND=python -c \"import aerospike\"" >> $GITHUB_ENV
+    #  shell: bash
+
+    #- name: Otherwise, enable integration tests
+    #  if: ${{ env.RUN_INTEGRATION_TESTS_IN_CIBW == 'true' }}
+    #  run: echo "TEST_COMMAND=cd ts-test;
+    #    npm install typescript --save-dev;
+    #    npx tsc;
+    #    cd ..;
+    #    npm run test dist/ -- --h 127.0.0.1 --port 3000" >> $GITHUB_ENV
+    #  shell: bash
+
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        name: nodejs-client-artifacts
+        path: ./downloaded-artifacts
+
+    - name: list Artifacts first
+      run: |
+        ls ./downloaded-artifacts
+        ls ./downloaded-artifacts/glibc@2.31
+        ls ./downloaded-artifacts/glibc@2.35
+
+    - name: Move artifacts
+      run: |
+        mkdir -p lib/binding
+        cp -r downloaded-artifacts/* lib/binding
+
+
+    - name: Delete leftover artifacts
+      if: ${{ !(inputs.platform-tag == 'win_amd64') }}
+      run: |
+        rm -rf downloaded-artifacts/
+
+    - name: check binding
+      run:
+        ls lib/binding;
+        ls lib/binding/glibc@2.35;
+        ls lib/binding/glibc@2.31;
+
+    - name: Change install command for release
+      run: node ./scripts/change-install-command.js
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && startsWith(inputs.platform-tag, 'manylinux') }}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cd ts-test;
+        npm install;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test dist/metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+        npm run test dist/metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+
+    - name: Run tests
+      if: ${{ inputs.run_tests && inputs.platform-tag == 'macosx_x86_64'}}
+      run: |
+        docker ps;
+        docker logs aerospike;
+        cd ts-test;
+        npm install;
+        npx tsc;
+        cd ..;
+        npx tsc;
+        npm run test dist/metrics_node_close.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+        npm run test dist/metrics_cluster_name.js -- --testMetrics true --h localhost --port 3000  --t 15000 --U superuser --P superuser;
+
+    - name: Set final commit status
+      uses: myrotvorets/set-commit-status-action@v2.0.0
+      if: ${{ always() && github.event_name != 'push' && github.event_name != 'pull_request' }}
+      with:
+        sha: ${{ env.COMMIT_SHA_TO_BUILD_AND_TEST }}
+        status: ${{ job.status }}
+        context: ${{ env.STATUS_CHECK_MESSAGE }}
 
   test-ce:
     needs: get-runner-os
